openapi: 3.1.0
info:
  title: Atomicwork Public accessManagement businessHourConfig API
  version: 1.0.0
servers:
- url: https://{tenant}.atomicwork.com
  description: Your Atomicwork tenant
tags:
- name: businessHourConfig
paths:
  /api/v1/workspaces/{workspace_id}/business-hour-config:
    get:
      operationId: getapi-v-1-workspaces-workspace-id-business-hour-config
      summary: Retrieve Business Hour Configurations
      tags:
      - businessHourConfig
      parameters:
      - name: workspace_id
        in: path
        description: The workspace ID
        required: true
        schema:
          type: integer
          format: int64
      - name: search_key
        in: query
        description: ''
        required: false
        schema:
          type: string
      - name: page
        in: query
        description: ''
        required: true
        schema:
          type: integer
          default: 1
      - name: per_page
        in: query
        description: ''
        required: false
        schema:
          type: integer
          default: 25
      - name: type
        in: query
        description: Automation entity type (see allowed values in the enum schema).
        required: false
        schema:
          $ref: '#/components/schemas/ApiV1WorkspacesWorkspaceIdBusinessHourConfigGetParametersType'
      - name: X-Api-Key
        in: header
        required: true
        schema:
          type: string
      - name: X-Workspace-Id
        in: header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business Hour Config_getapi_v1_workspaces__workspace_id__business_hour_config_Response_200'
  /api/v1/workspaces/{workspace_id}/business-hour-config/{id}:
    get:
      operationId: getapi-v-1-workspaces-workspace-id-business-hour-config-id
      summary: Retrieve Business Hour Configurations
      tags:
      - businessHourConfig
      parameters:
      - name: workspace_id
        in: path
        description: The workspace ID
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        description: The business hour configuration ID
        required: true
        schema:
          type: integer
          format: int64
      - name: X-Api-Key
        in: header
        required: true
        schema:
          type: string
      - name: X-Workspace-Id
        in: header
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business Hour Config_getapi_v1_workspaces__workspace_id__business_hour_config__id_Response_200'
components:
  schemas:
    ApiV1WorkspacesWorkspaceIdBusinessHourConfigGetParametersType:
      type: string
      enum:
      - DROPDOWN
      - LIST
      title: ApiV1WorkspacesWorkspaceIdBusinessHourConfigGetParametersType
    Business Hour Config_getapi_v1_workspaces__workspace_id__business_hour_config__id_Response_200:
      type: object
      properties: {}
      description: Empty response body
      title: Business Hour Config_getapi_v1_workspaces__workspace_id__business_hour_config__id_Response_200
    Business Hour Config_getapi_v1_workspaces__workspace_id__business_hour_config_Response_200:
      type: object
      properties: {}
      description: Empty response body
      title: Business Hour Config_getapi_v1_workspaces__workspace_id__business_hour_config_Response_200
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
